#!/bin/bash

################################################################################
# SLURM Array Job Generator for ASTEP Calibration Pipeline
#
# This script automatically discovers date directories and submits a SLURM
# array job to process them in parallel. Each date is processed on a separate
# compute node.
#
# Usage: ./scripts/submit_cal_array.sh <data_path> [OPTIONS]
#
# Arguments:
#   data_path: Path to directory containing date subdirectories (YYYY-MM-DD)
#
# Options:
#   --mem MEM         Memory per job in GB (default: 16)
#   --time TIME       Time limit per job (default: 04:00:00)
#   --partition NAME  SLURM partition name (default: sched_mit_hill)
#   --force           Force recalibration even if calibrated files exist
#   --dry-run         Show what would be submitted without actually submitting
#
# Examples:
#   ./scripts/submit_cal_array.sh /path/to/data
#   ./scripts/submit_cal_array.sh /path/to/data --mem 32 --time 08:00:00
#   ./scripts/submit_cal_array.sh /path/to/data --force --dry-run
################################################################################

# Default values
MEM_LIMIT="16"
TIME_LIMIT="04:00:00"
PARTITION="sched_mit_hill"
FORCE_FLAG=""
DRY_RUN=false

# Parse command-line arguments
if [ $# -lt 1 ]; then
    echo "Error: Data path not provided"
    echo "Usage: $0 <data_path> [OPTIONS]"
    echo ""
    echo "Options:"
    echo "  --mem MEM         Memory per job in GB (default: 16)"
    echo "  --time TIME       Time limit per job (default: 04:00:00)"
    echo "  --partition NAME  SLURM partition name (default: sched_mit_hill)"
    echo "  --force           Force recalibration"
    echo "  --dry-run         Show what would be submitted without submitting"
    exit 1
fi

DATA_PATH="$1"
shift

# Parse optional arguments
while [[ $# -gt 0 ]]; do
    case "$1" in
        --mem)
            MEM_LIMIT="$2"
            shift 2
            ;;
        --time)
            TIME_LIMIT="$2"
            shift 2
            ;;
        --partition)
            PARTITION="$2"
            shift 2
            ;;
        --force)
            FORCE_FLAG="--force"
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Validate data path
if [ ! -d "$DATA_PATH" ]; then
    echo "ERROR: Data path does not exist: $DATA_PATH"
    exit 1
fi

# Discover date directories
echo "Discovering date directories in $DATA_PATH..."
DATES=()
for date_dir in "$DATA_PATH"/*; do
    if [ ! -d "$date_dir" ]; then
        continue
    fi

    date=$(basename "$date_dir")

    # Validate YYYY-MM-DD format
    if [[ "$date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
        DATES+=("$date")
    fi
done

if [ ${#DATES[@]} -eq 0 ]; then
    echo "ERROR: No date directories found in $DATA_PATH"
    echo "Expected directories matching pattern: YYYY-MM-DD"
    exit 1
fi

echo "Found ${#DATES[@]} date(s) to process:"
for date in "${DATES[@]}"; do
    echo "  - $date"
done
echo ""

# Get repository root directory
REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)

# Create temporary SLURM submission script
TEMP_SCRIPT=$(mktemp /tmp/astep_cal_submit_XXXXXX.sh)

# Write the submission script
cat > "$TEMP_SCRIPT" << 'SUBMIT_SCRIPT_EOF'
#!/bin/bash
#SBATCH --job-name=astep_cal
#SBATCH --output=logs/cal_%A_%a.out
#SBATCH --error=logs/cal_%A_%a.err

# This script is auto-generated by submit_cal_array.sh

# Job configuration (will be set by sed replacements)
DATA_BASE_DIR="__DATA_PATH__"
MEM_LIMIT="__MEM_LIMIT__"
FORCE_FLAG="__FORCE_FLAG__"
CONDA_ENV="astep"

# Date array (will be populated by sed)
DATES=(
__DATES_ARRAY__
)

# Create logs directory
mkdir -p logs

# Print job information
echo "==============================================="
echo "ASTEP Calibration Job Information"
echo "==============================================="
echo "Job ID: $SLURM_JOB_ID"
echo "Array Task ID: $SLURM_ARRAY_TASK_ID"
echo "Node: $SLURM_NODELIST"
echo "Memory: $SLURM_MEM_PER_NODE MB"
echo "Start Time: $(date)"
echo "==============================================="
echo ""

# Select date based on array index
if [ -z "$SLURM_ARRAY_TASK_ID" ]; then
    echo "ERROR: SLURM_ARRAY_TASK_ID not set"
    exit 1
fi

if [ "$SLURM_ARRAY_TASK_ID" -ge "${#DATES[@]}" ]; then
    echo "ERROR: Array index $SLURM_ARRAY_TASK_ID exceeds DATES array size ${#DATES[@]}"
    exit 1
fi

DATE_TO_PROCESS="${DATES[$SLURM_ARRAY_TASK_ID]}"
DATA_PATH="$DATA_BASE_DIR/$DATE_TO_PROCESS"

echo "Processing date: $DATE_TO_PROCESS"
echo "Data path: $DATA_PATH"
echo ""

# Check if data path exists
if [ ! -d "$DATA_PATH" ]; then
    echo "ERROR: Data path does not exist: $DATA_PATH"
    exit 1
fi

# Initialize conda
source $(conda info --base)/etc/profile.d/conda.sh

# Activate environment
echo "Activating $CONDA_ENV environment..."
conda activate $CONDA_ENV

if [ "$CONDA_DEFAULT_ENV" != "$CONDA_ENV" ]; then
    echo "ERROR: Failed to activate $CONDA_ENV environment"
    exit 1
fi

# Navigate to repository root
cd "__REPO_ROOT__" || exit 1

# Run calibration
echo "==============================================="
echo "Running calibration pipeline..."
echo "==============================================="
echo ""

./scripts/cal.sh "$DATA_PATH" --mem-limit $MEM_LIMIT $FORCE_FLAG

EXIT_STATUS=$?

echo ""
echo "==============================================="
echo "Job completed with exit status: $EXIT_STATUS"
echo "End Time: $(date)"
echo "==============================================="

exit $EXIT_STATUS
SUBMIT_SCRIPT_EOF

# Build dates array string for the script
DATES_STRING=""
for date in "${DATES[@]}"; do
    DATES_STRING+="    \"$date\"\n"
done

# Perform replacements
sed -i.bak "s|__DATA_PATH__|$DATA_PATH|g" "$TEMP_SCRIPT"
sed -i.bak "s|__MEM_LIMIT__|$MEM_LIMIT|g" "$TEMP_SCRIPT"
sed -i.bak "s|__FORCE_FLAG__|$FORCE_FLAG|g" "$TEMP_SCRIPT"
sed -i.bak "s|__REPO_ROOT__|$REPO_ROOT|g" "$TEMP_SCRIPT"
sed -i.bak "/__DATES_ARRAY__/c\\
$DATES_STRING
" "$TEMP_SCRIPT"

# Remove backup file
rm -f "${TEMP_SCRIPT}.bak"

# Calculate array range
ARRAY_MAX=$((${#DATES[@]} - 1))

# Construct sbatch command
SBATCH_CMD="sbatch --array=0-${ARRAY_MAX} --mem=${MEM_LIMIT}G --time=${TIME_LIMIT} --partition=${PARTITION}"

# Display submission information
echo "==============================================="
echo "SLURM Array Job Submission"
echo "==============================================="
echo "Number of jobs: ${#DATES[@]}"
echo "Array range: 0-${ARRAY_MAX}"
echo "Memory per job: ${MEM_LIMIT}G"
echo "Time limit: ${TIME_LIMIT}"
echo "Partition: ${PARTITION}"
if [ -n "$FORCE_FLAG" ]; then
    echo "Force recalibration: YES"
fi
echo ""
echo "Submission command:"
echo "$SBATCH_CMD $TEMP_SCRIPT"
echo "==============================================="
echo ""

if [ "$DRY_RUN" = true ]; then
    echo "DRY RUN - Not submitting job"
    echo "Generated script saved to: $TEMP_SCRIPT"
    echo ""
    echo "Script contents:"
    echo "==============================================="
    cat "$TEMP_SCRIPT"
    echo "==============================================="
else
    # Submit the job
    echo "Submitting job..."
    JOB_OUTPUT=$($SBATCH_CMD "$TEMP_SCRIPT" 2>&1)
    EXIT_CODE=$?

    echo "$JOB_OUTPUT"
    echo ""

    if [ $EXIT_CODE -eq 0 ]; then
        # Extract job ID from output
        JOB_ID=$(echo "$JOB_OUTPUT" | grep -oP '(?<=Submitted batch job )\d+')
        echo "SUCCESS: Job submitted with ID $JOB_ID"
        echo ""
        echo "Monitor job status with:"
        echo "  squeue -u \$USER"
        echo "  squeue -j $JOB_ID"
        echo ""
        echo "View logs in:"
        echo "  logs/cal_${JOB_ID}_*.out"
        echo "  logs/cal_${JOB_ID}_*.err"

        # Clean up temp script
        rm -f "$TEMP_SCRIPT"
    else
        echo "ERROR: Job submission failed"
        echo "Generated script saved to: $TEMP_SCRIPT"
        exit 1
    fi
fi
